title: Team Service Center
baseurl: /service
markdown: kramdown
# gems: [jekyll-paginate]
# paginate: 5
# paginate_path: "questions/page:num"


#--------------------------------
# Teams

teams:
- {name: Team BJTU, abr: bjt, title: i-Yard 2.0}
- {name: Team HKU, abr: hku, title: S(L)OW House}
- {name: Team Israel, abr: isr, title: The Cactus Home, dd: 18 Nov 2016 }
- {name: Team Istanbul, abr: ist, title: ALGAETECH House}
- {name: Team JIA+, abr: jia, title: JIA+ }
- {name: Team Montreal, abr: mon, title: Deep-Performance Dwelling}
- {name: Team NJFT, abr: njf, title: DOTTIE}
- {name: Team SCUT-POLITO, abr: scu, title: SCUT-POLITO}
- {name: Team SEU-TUBS, abr: seu, title: SEU-TUBS}
- {name: Team Shunya, abr: shu, title: Project Solarise}
- {name: Team SIE, abr: sie, title: Smart Nest}
- {name: Team SJTUIUC, abr: sjt, title: SJTUIUC}
- {name: Team Solar Offspring, abr: sol, title: R. E. A. L House}
- {name: Team SSA, abr: ssa, title: PUR-e House}
- {name: Team SUES-XD, abr: sue, title: Dancing Sunlight}
- {name: Team THU, abr: thu, title: WHAO House}
- {name: Team TJU-TUD, abr: tju, title: Solar House}
- {name: Team Toronto, abr: tor, title: Stacked Home}
- {name: Team UNNC Alpha, abr: unn, title: Duo Pension House}
- {name: Team XAUAT, abr: xau, title: Qiju 2.0}
- {name: Team Xi'an Mass, abr: xia, title: Xi'an Mass}
- {name: Team YI, abr: yi, title: YI}
